var error_codes = {

	NONE: "ERR_NONE",
	UNKNOWN: "ERR_UNKNOWN",
	PASSPORT_DOESNT_EXIST: "ERR_PASSPORT_DOESNT_EXIST",
	DB_ERROR: "ERR_DB_ERROR",
	PASSPORT_CONFLICT: "ERR_PASSPORT_CONFLICT",
	USER_EXISTS: "ERR_USER_EXISTS",
	USER_DOESNT_EXIST: "ERR_USER_DOESNT_EXIST",
	INTERNAL_PASSPORT_ERROR: "ERR_INTERNAL_PASSPORT_ERROR",
	PASSPORT_FAILED_VALIDATION: "ERR_PASSPORT_FAILED_VALIDATION",
	PASSPORT_FAILED_AUTHENTICATION: "ERR_PASSPORT_FAILED_AUTHENTICATION",
	USER_CREATION_FAILED: "ERR_USER_CREATION_FAILED",
	TOKEN_ERROR: "ERR_TOKEN_ERROR",
	NO_CONTENT_PROVIDED: "ERR_NO_CONTENT_PROVIDED",
	FAILED_USER_SAVE: "ERR_FAILED_USER_SAVE",
	COULD_NOT_FIND_USER: "ERR_COULD_NOT_FIND_USER",
	AUTHTOKEN_MISSING: "ERR_AUTHTOKEN_MISSING",
	MISSING_SCORE: "ERR_MISSING_SCORE",
	INCORRECT_PROPERTY: "ERR_INCORRECT_PROPERTY",
	USER_HAS_NO_SCORE: "ERR_USER_HAS_NO_SCORE",
	GROUP_ALREADY_EXISTS: "ERR_GROUP_ALREADY_EXISTS",
	DATA_NOT_VALID: "ERR_DATA_NOT_VALID",
	NO_CHANNEL_EXISTS: "ERR_CHANNEL_DOES_NOT_EXIST"

};


module.exports = error_codes;